language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - CAKE_VERSION=2.3.10 DB=mysql
  - CAKE_VERSION=2.4.10 DB=mysql
  - CAKE_VERSION=master DB=mysql

install:
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKE_VERSION
  - cp -R ../chatwork_cakephp plugins/Chatwork
  - chmod -R 777 ../cakephp/app/tmp
  - sh -c "composer global require 'phpunit/phpunit=3.7.33'"
  - sh -c "ln -s ~/.composer/vendor/phpunit/phpunit/PHPUnit ../cakephp/vendors/PHPUnit"

notifications:
  email: false
